"""Render docs/decisions/DEPENDENCY_MATRIX.md from the audit JSON files."""
import json
from pathlib import Path

root = Path("docs/decisions")
pypi = json.loads((root / "pypi_audit.json").read_text(encoding="utf-8"))
gh = json.loads((root / "github_audit.json").read_text(encoding="utf-8"))

def kind(r):
    if r.get("error"):
        return "not found"
    if r["cp314_native_wheel"]:
        return "native cp314 wheel"
    if r["cp314_win_wheel"]:
        return "pure/abi3 wheel"
    return "NO wheel (sdist only)" if r["has_sdist"] else "NO wheel"

lines = [
    "# Dependency compatibility matrix (CPython 3.14, Windows x64)",
    "",
    "Generated by `scripts/audit_deps.py` + `scripts/render_matrix.py` from live PyPI/GitHub data.",
    "Wheel column is derived from wheel filename tags only (installability on cp314/win_amd64);",
    "it does not prove runtime correctness. CUDA/Blackwell status is covered separately in",
    "`docs/ARCHITECTURE_AUDIT.md` (section 4) where it was actually tested.",
    "",
    "## PyPI packages",
    "",
    "| Package | Latest | Released | License | requires-python | cp314 win wheel | Notes |",
    "|---|---|---|---|---|---|---|",
]
notes = {
    "google-generativeai": "Legacy SDK; migrate to google-genai.",
    "kokoro": "requires-python <3.13 -> must run isolated.",
    "kokoro-onnx": "requires-python <3.14 -> must run isolated.",
    "misaki": "requires-python <3.13 (kokoro G2P).",
    "piper-tts": "GPL-3.0-or-later: use only as separate process, never import.",
    "homeassistant-api": "GPL-3.0-or-later: do not link; use plain REST via httpx.",
    "edge-tts": "Calls an online Microsoft service; LGPL.",
    "pystray": "LGPLv3 (dynamic use only).",
    "pynput": "LGPLv3.",
    "pyautogui": "sdist-only (pure Python, builds locally); stale since 2023.",
    "webrtcvad": "No wheels, last release 2017; use silero-vad.",
    "pyaudio": "No cp314 wheel; use sounddevice.",
    "windows-mcp": "requires-python >=3.14; depends on fastmcp>=3, posthog (telemetry). Run isolated.",
    "mcp": "2.x is stable (see ADR-0001).",
    "keyboard": "Unmaintained since 2020; avoid.",
    "openwakeword": "Last PyPI release 2024-02; ONNX path only on Windows.",
}
for r in pypi:
    if r.get("error"):
        lines.append(f"| {r['name']} | - | - | - | - | {r['error']} | |")
        continue
    lines.append(
        f"| {r['name']} | {r['version']} | {(r['released'] or '')[:10]} | {(r['license'] or '').replace('|','/')[:40]} "
        f"| {r['requires_python']} | {kind(r)} | {notes.get(r['name'], '')} |"
    )
lines += ["", "## GitHub repositories", "",
          "| Repo | License | Archived | Stars | Last push | Latest release |", "|---|---|---|---|---|---|"]
for r in gh:
    if r.get("error"):
        lines.append(f"| {r['repo']} | - | - | - | - | {r['error']} (moved or renamed) |")
        continue
    lines.append(
        f"| {r['repo']} | {r['license']} | {r['archived']} | {r['stars']} | {(r['pushed_at'] or '')[:10]} "
        f"| {r['latest_release'] or '-'} {(r['latest_release_date'] or '')[:10]} |"
    )
(root / "DEPENDENCY_MATRIX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("ok", len(lines))
